#!/bin/bash

# Name: Ty Bradley
# Course: COMP2137 - Linux Automation
# Professor: Dennis Simpson
# Date: October 4th, 2023

# The purpose of this script is to display some important identity information about a computer so that you can see that information quickly and concisely, without having to memorize mutliple commands or remember multiple command options.

# Enstantiating variable names for script begins here
#-----------------------------------------------------

# Variable for current user name.
USERNAME=$(whoami)

# Variable for current date.
CURRENTDATE=$(echo "null")

# Variable for current host.
HOSTNAME=$(echo "null")

# Variable for current Linux Distrobution with version.
DISTROWITHVERSION=$(echo "null")

# Current uptime.
UPTIME=$(echo "null")

# Current CPU information.
CPUINFO=$(echo "null")

# Current and Max Speed of CPU
CURRENTANDMAXSPEEDCPU=$(echo "null")

# Current size of RAM allotted to VM
SIZERAM=$(echo "null")

# Make and model of video card
MAKEMODELVGU=$(echo "null")

# Make, model, and size for all installed disks.
MAKEMODELSIZEDISK=$(echo "null")

# Fully qualified domain name
FQDN=$(echo "null")

# Lists all users currently logged into the system
USERSLOGGEDIN=$(echo "null")

# Shows free space for local filesystems in format: / MOUNTPOINT N
FREEDISKSPACE=$(echo "null")

# Lists process count
PROCESSCOUNT=$(echo "null")

# Lists load averages
LOADAVERAGES=$(echo "null")

# Lists memory allocation
MEMORYALLOCATION=$(echo "null")

# Lists currently listening network ports
LISTENINGNETWORKPORTS=$(echo "null")

# Lists data from UFW Show
UFWRULES=$(echo "null")

# Enstantiating variable names for script ends here
#-----------------------------------------------------

echo "
System Report generated by $USERNAME, $CURRENTDATE

------------------ 
System Information
------------------

`# Current Hostname within system.`
Hostname: $HOSTNAME
`# Current Linux OS distribution within system.`
OS: $DISTROWITHVERSION
`# Current uptime of system.`
Uptime: $UPTIME

-------------------- 
Hardware Information
--------------------

`#cpu: PROCESSOR MAKE AND MODEL`
cpu: $CPUINFO
`#Speed: CURRENT AND MAXIMUM CPU SPEED`
Speed: $CURRENTANDMAXSPEEDCPU
`#Ram: SIZE OF INSTALLED RAM`
Ram: $SIZERAM
`#disk(s): MAKE AND MODEL AND SIZE FOR ALL INSTALLED DISKS`
Disk(s): $MAKEMODELSIZEDISK
`#Video: MAKE AND MODEL OF VIDEO CARD`
Video: $MAKEMODELVGU

------------------- 
Network Information
-------------------

# Fully Qualified Domain Name
FQDN: $FQDN
# IP Address for the hostname
Host Address: $IPHOST
# IP Address for the Gateway
Gateway IP: $GATEWAYIP
# IP Address of the DNS Server
DNS Server: $DNSIP
# Make and model of network card
InterfaceName: $NETCARD
# IP Address in CIDR FORMAT
IP Address: $IPCIDR

------------- 
System Status
-------------

# Lists all users currently logged into the system
Users Logged In: $USERSLOGGEDIN
# Shows free space for local filesystems in format: / MOUNTPOINT N
Disk Space: $FREEDISKSPACE
# Lists process count
Process Count: $PROCESSCOUNT
# Lists load averages
Load Averages: $LOADAVERAGES
# Lists memory allocation
Memory Allocation: $MEMORYALLOCATION
# Lists currently listening network ports
Listening Network Ports: $LISTENINGNETWORKPORTS
# Lists data from UFW Show
UFW Rules: $UFWRULES

"
#End of File